import type { HouseItem } from '@/api/house'

export const mockHouses: HouseItem[] = [
  {
    id: 9001,
    landlordId: 101,
    title: '万柳书院旁南向两居，近地铁16号线',
    description: '采光稳定，家具家电齐全，适合通勤中关村和海淀黄庄。',
    area: '海淀区',
    address: '万柳中路 · 蜂鸟家园',
    longitude: 116.3048,
    latitude: 39.9772,
    price: 6800,
    houseType: '两居',
    rentType: '整租',
    areaSize: 72,
    floor: '8/18层',
    decoration: '精装',
    orientation: '南向',
    subwayDistance: 520,
    subwayStation: '苏州桥',
    hasElevator: 1,
    hasParking: 1,
    facilities: ['空调', '洗衣机', '电梯', '独立阳台'],
    status: 1,
    viewCount: 248,
    collectCount: 36,
    avgRating: 4.8,
    reviewCount: 19,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'],
    tags: ['近地铁', '采光好', '可长租'],
  },
  {
    id: 9002,
    landlordId: 102,
    title: '朝阳公园精装一居，独立阳台可养宠',
    description: '周边生活配套成熟，楼下便利店、咖啡店和健身房。',
    area: '朝阳区',
    address: '甜水园街 · 公园1872',
    longitude: 116.4784,
    latitude: 39.9336,
    price: 5200,
    houseType: '一居',
    rentType: '整租',
    areaSize: 48,
    floor: '12/22层',
    decoration: '精装',
    orientation: '东南',
    subwayDistance: 780,
    subwayStation: '朝阳公园',
    hasElevator: 1,
    hasParking: 0,
    facilities: ['冰箱', '空调', '燃气灶', '阳台'],
    status: 1,
    viewCount: 186,
    collectCount: 22,
    avgRating: 4.6,
    reviewCount: 12,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80'],
    tags: ['可养宠', '独立阳台', '公园旁'],
  },
  {
    id: 9003,
    landlordId: 103,
    title: '西二旗合租主卧，互联网园区通勤友好',
    description: '室友稳定，公共区域整洁，适合单人入住。',
    area: '昌平区',
    address: '回龙观西大街 · 龙泽苑',
    longitude: 116.3192,
    latitude: 40.0709,
    price: 2600,
    houseType: '主卧',
    rentType: '合租',
    areaSize: 22,
    floor: '5/6层',
    decoration: '简装',
    orientation: '南向',
    subwayDistance: 640,
    subwayStation: '龙泽',
    hasElevator: 0,
    hasParking: 0,
    facilities: ['空调', '洗衣机', '热水器', '宽带'],
    status: 1,
    viewCount: 319,
    collectCount: 44,
    avgRating: 4.5,
    reviewCount: 27,
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80'],
    tags: ['合租', '通勤友好', '性价比'],
  },
]

export const mockMessages = [
  {
    id: 7001,
    msgType: 'appointment',
    title: '看房预约已确认',
    content: '你预约的“万柳书院旁南向两居”已确认，今天 18:30 可到现场看房。',
    isRead: 0,
    createTime: '今天 10:24',
  },
  {
    id: 7002,
    msgType: 'system',
    title: '房源推荐更新',
    content: '根据你的偏好，新增 3 套海淀区近地铁房源。',
    isRead: 0,
    createTime: '昨天 21:18',
  },
  {
    id: 7003,
    msgType: 'bill',
    title: '租金账单提醒',
    content: '6 月账单已生成，请在 7 月 5 日前完成支付。',
    isRead: 1,
    createTime: '06-28 09:12',
  },
]
